[env]
framework = arduino
platform = espressif32
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 1500000

build_flags =
  -std=c++17
  -Wall
  -Wextra
  -Wno-deprecated-declarations
  -DCORE_DEBUG_LEVEL=3

[env:m5stack-dial]
lib_deps =
  m5stack/M5Dial
  m5stack/M5GFX
  m5stack/M5Unified

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
